name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

strategy:
  matrix:
    compiler: [g++-11]

env:
  CC = {{ matrix.compiler }}

jobs:
  release-build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make MODE=RELEASE

  debug-build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make MODE=DEBUG