name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  make-release-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: make
        run: make MODE=RELEASE

  cmake-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: build directory
        run: mkdir build && cd build
      - name: generate cmake files
        run: cmake -Bbuild
      - name: build
        run: cmake --build build